version: "3.9"
services:
  net-core-app:
    image: beginor/net-core-app
    hostname: net-core-app
    ports:
      - 5000:80
    volumes:
      - ./log:/net-core-app/log
    environment:
      TZ: Asia/Shanghai
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped
networks:
  default:
    external: true
    name: compose
